class Diseases:
    diseases = [
        ["allergic rhinitis or hay fever", "runny nose", "stuffy nose", "sneezing", "itchy nose", "itchy eyes","itchy ears", "itchy throat", "postnasal drip"],
        ["asthma", "shortness of breath", "wheezing", "coughing", "chest tightness"],
        ["allergic eyes or conjunctivitis", "redness under the lids and of the eye overall", "watery, itchy eyes","swelling of the membranes"],
        ["eczema or atopic dermatitis", "dry skin"],
        ["Cancer", "peeing at different times", "using the bathroom at unusual times", "a persistent sore throat", "bleeding in weird places"],
        ["angina", "chest pain", "nausea", "fatigue", "shortness of breath", "sweating", "dizziness"],
        ["congenital heart defect", "fatigue", "rapid breathing", "poor circulation"],
        ["heart attack", "chest pain"],
        ["stroke", "face drooping", "arm weakness", "speech difficulty"],
        ["ADHD", "difficulty concentrating", "very active", "impulsive"],
        ["chickenpox", "fever", "red spots", "blisters", "rash"],
        ["pink eye", "cough", "earache", "eye discharge", "eye pain", "eye redness", "itchy eyes", "runny nose","swollen eyelids"],
        ["measles", "cough", "runny nose", "high fever"],
        ["mumps", "fever", "headache", "muscle ache", "loss of appetite", "malaise"],
        ["anorexia nervosa", "low blood pressure", "low blood density", "thirst"],
        ["bulimia", "sore throat","discolored","deteriorating teeth","abdominal pain","cramping","bloating","vomitting"],
        ["cellulite", "dimpling of the skin", "orange skin", "peeling skin"],
        ["bladder infection", "dysuria", "urinary frequency", "urinary urgency", "pain above the pelvic bone","blood in urine"],
        ["cystinuria", "blood in urine", "pain in my side", "intense cramping", "cramping"],
        ["interstitial cystitis", "frequent urination", "pain around the bladder", "painful sexual intercourse","pain in the penis", "pain in the scrotum"],
        ["kidney stones", "flank pain", "blood in urine"],
        ["prostatitis", "painful urination", "blood in urine", "groin pain", "fever", "chills", "body aches","urethral discharge", "painful sexual intercourse"],
        ["urethral stricture", "difficulty urinating", "painful urination", "urinary track infection","incomplete emptying of bladder", "blood in urine", "pelvic pain", "stones in bladder", "frequent urination"],
        ["urinary track infection", "inflamed bladder", "irritated bladder", "frequent urination", "urinary urgency","smelly urine", "fever", "chills"],
        ["breast cancer", "lump in breast", "lump in armpit", "bloody nipple", "inverted nipple", "orange peel breasts","breast pain", "swollen lymph nodes", "change in the size of breasts", "change in the shape of breasts"],
        ["menopause", "vaginal bleeding", "hot flashes", "vaginal and urinary symptoms", "mood changes"],
        ["osteoporosis", "bone pain", "breaking bones"],
        ["ovarian cancer", "fatigue", "getting full quickly", "abdominal swelling", "leg swelling","shortness of breath"],
        ["yeast infection", "itching of genitals", "burning of genitals", "painful urination"],
        ["hashimoto's thyroiditis", "fatigue", "depression", "weight gain", "coid intolerance", "excessive sleepiness","dry skin", "muscle cramps", "decreased concentration", "increased cholesterol levels", "leg swelling"],
        ["hyperthyroidism", "excessive sweating", "heat intolerance", "increased bowel movements", "tremor","nervousness", "anxiety", "rapid heart rate", "weight loss", "fatigue", "decreased concentration","thinning skin", "sleep disturbance"],
        ["hypothyroidism", "depression", "fatigue", "weight gain", "cold intolerance", "excessive sleepiness","constipation", "dry skin", "muscle cramps", "increased cholesterol levels", "decreased concentration","vauge ahces", "leg swelling"],
        ["levothyroxine", "chest pain", "increased heart rate", "excessive sweating", "heat intolerance", "nervousness","headache", "insomnia", "diarrhea", "vomiting", "weight loss", "fever"],
        ["thyroid cancer", "lump in the front of the neck", "lump in the throat", "difficulty swallowing", "esophagus","paralysis", "strep throat", "ear infections"],
        ["narcolepsy", "excessive daytime sleepiness", "excessive sleepiness", "cataplexy", "hallucinations","sleep paralysis", "automatic behavior", "blurred vision", "double vision"],
        ["sleep apnea", "snoring", "gasping for air", "insomnia", "restless sleep"],
        ["actinic keratosis", "large pimples", "large acne"],
        ["melanoma", "asymetric mole", "mole with irregular border", "mole with irregular color", "large mole","changing mole"],
        ["nail fungus", "oddly colored nails", "deteriorating nails", "nail pain"],
        ["poison ivy", "red skin", "skin swelling", "itchy skin", "blisters"],
        ["psoriasis", "red bumps", "pink bumps", "scaly bumps", "itchy skin", "elbow bumps", "knee bumps"],
        ["rosacea", "small pimples", "eye swelling", "itch eyes", "red eyes", "facial pimples"],
        ["scleroderma", "skin swelling", "itchy skin", "painful skin", "difficulty swallowing", "chest pain"],
        ["shingles", "skin bumps", "blisters", "rash", "chills", "diarrhea", "headaches"],
        ["skin cancer", "shiny bumps", "red bumps", "pink bumps", "pink skin", "itchy skin", "open sores", "warts","wart growth"],
        ["alzheimers", "memory loss", "difficulty performing tasks", "difficulty talking", "difficulty writing","disorientation to time", "disorientation to location", "vision problems", "mood changes"],
        ["anemia", "fatigue", "paleness", "shortness of breath", "heart racing", "heart problems"],
        ["angina", "chest pain", "nausea", "shortness of breath", "excessive sweating", "fatigue", "dizziness"],
        ["cataracts", "vision problems", "double vision", "eye pain"],
        ["dementia", "forgetfulness", "memory loss", "weight loss", "difficulty talking to others","difficulty performing tasks"],
        ["glaucoma", "vision problems", "loss of vision", "eye pain", "headaches", "nausea", "vomiting"],
        ["common cold", "cough”, “sore","throat", "sneezing", "runny","nose"],
        ["body dysmorphic disorder", "acne", "scarring", "facial lines", "pale skin", "thinning hair", "crooked nose"],
        ["panic attack", "racing heart", "chest pain", "upset stomach", "dizziness", "hyperventilation", "hot flashes","fear of dying", "choking sensation"],
        ["separation anxiety", "heightened concern", "fear of loss", "refusal to sleep", "repeating nightmares","headaches"],
        ["benign prostatic hyperplasia", "slow urination", "painful urination"],
        ["prostate cancer", "frequent urination", "difficulty urinating", "blood in urine"],
        ["testicular cancer", "lumps around testicles", "testicle swelling", "change in how testicles feel", "groin acne","abdomen acne", "testicle pain", "scrotum pain"],
        ["asthma", "family history of allergies", "obesity", "wheezing", "shortness of breath", "cough"],
        ["chronic obstructive pulmonary disease", "cough", "chest pain", "shortness of breath", "wheezing","rapid breathing", "over inflated lungs"],
        ["lung cancer", "difficulty swallowing", "difficulty breathing", "cough", "shortness of breath", "wheezing","chest pain", "headaches", "fatigue", "weight loss"],
        ["pneumonia", "fever", "chills", "cough", "shortness of breath", "fatigue"],
        ["hepatitis B", "weakness", "fatigue", "weight loss", "palm rashes", "blood clotting", "loss of appetite"],
        ["hepatitis C", "fatigue", "loss of appetite", "muscle aches", "fever", "abdominal pain", "confusion","weight loss"],
        ["malaria", "fever", "headaches", "nausea", "vomiting", "weakness", "low blood sugar", "kidney failure"],
        ["meningitis", "sudden fever", "fever", "vomiting", "headaches", "stiff neck", "stiff back", "unsteady gait","confusion", "seizures", "weakness", "memory loss"],
        ["AIDS", "weight loss", "fatigue", "pneumonia", "seizures"],
        ["pink eye", "cough", "eye pain", "earaches", "itchy eyes", "swollen eyes", "tearing", "runny nose", "red eyes"]

    ]